apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.image.tag }}
        name: {{ .Values.app.name }}
        ports:
        - containerPort: {{ .Values.service.containerPort }}
        env:
          {{- toYaml .Values.env | nindent 12}}  
        resources: {} 
status: {}