replicaCount: 2
app:
  name: myapp
image:
  repository: bhuwan405
  pullPolicy: IfNotPresent
  tag: "test-app:36"
service:
  name: myapp
  type: ClusterIP
  containerPort: 3000
  port: 80
env:
  - name: MONGODB_HOST
    valueFrom:
      secretKeyRef:
        name: myapp
        key: MONGODB_HOST
  - name: MONGODB_PORT
    valueFrom:
      secretKeyRef:
        name: myapp
        key: MONGODB_PORT
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.org/client-max-body-size: 50M
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - myapp.local
